{% set name = "ccaffeine" %}
{% set version = "0.8.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  patches:
    - cxxflags-linux.patch [linux]
    - cxxflags-osx.patch [osx]

requirements:
  build:
    - python
    - libxml2
    - cca-spec-babel
    - cca-babel
    - boost-headers 1.34
    - readline
    - ncurses

  run:
    - python
    - libxml2
    - cca-spec-babel
    - cca-babel
    - readline
    - ncurses

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}
