{% set name = "ccaffeine" %}
{% set version = "0.8.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  patches:
    - cxxflags-linux.patch [linux]
    - cxxflags-osx.patch [osx]

requirements:
  build:
    - python >=2.7.13
    - numpy
    - libxml2
    - cca-spec-babel
    - cca-babel <2
    - boost-headers 1.34
    - readline
    - ncurses

  run:
    - python >=2.7.13
    - numpy
    - libxml2
    - cca-spec-babel
    - cca-babel <2
    - readline
    - ncurses

build:
  number: 1
