language: java
os:
- linux
- osx
env:
  matrix:
  - NUMPY_VERSION="1.11"
  - NUMPY_VERSION="1.12"
  - NUMPY_VERSION="1.13"
  global:
  - THIS_PACKAGE=ccaffeine
  - BUILD_STR="dev"
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: Bn8+dlF3rGiPCDquWPfX6+V7i+j1x4d3MNuF/xnDGD9FHPl54lrapA1GKZBUZpE9YFYCAYThtnkpdeWfcczmigk2nmSnrh/2rWUepFo5LKuRzMPyX3OjSB8zL3iHsfbEYymQL4SNpyphVmATuW2BLZMWoecZtMjCx8/UQPjNMlC4N4yAPisiIDBsf+w4kez3K3wmMVih3I3gcbCoKJUCxH09T99nwTy+QaoPckrsPIspdnlPSlgiqUNmj0H9q1KS5FzjJuljXfSbdGWwhEcEv15NHn1eDB8nMFoRI6jG7pXaQksRmEflW8vF+nmax3R9vVw357ikgJ/Arz2q4Ke3Jm63AG86U37/RE85+m4GFYq1N4FfSZNagPakScZnA2oIDPnA4z8rrM1pXnIqpnCEc4yVtV20mnMBAEhp8X2e+rfBa0xiLOyP237g6/51p86D2MXKD96zfHcqpvllMgpUS5a0lu7SK1JojUE3487rBpD/WwPzuwfIfl4qM+2RvrezjUAzPV26WT0Evc9aHyW+Nj8B00AGSiNoKxFXmbXwin3mcxI45r7hFzU7nPMC5T7OQAN622Z8CzfqsbaDrDOeSRQtXvy95VYM4atO6mT+3Jxcmk+UZX6MkC0jLaDXdFTkxmgh84U4Kzf5awk7N+fI+AQ9ntfEacdKYzPJBTOUVBc=
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build ./recipe --numpy=$NUMPY_VERSION -c csdms-stack -c conda-forge
after_success:
- if [[ $TRAVIS_BRANCH == "master" ]]; then export CHANNEL="main"; fi
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
